
# Configuration

title: Irvin Herrera
author: Irvin Herrera
email: irvin.herrerag@gmail.com
language: 'en-us'
description: >
  Hello ! Thanks for visiting :)
url: 'http://herrirvin.com'
twitter_username: irvinhg
google_analytics: TODO
baseurl: ""
show_dir_listing: false
year: 2016
permalink: "/blog/:year-:title"

# Tags : Using 'jekyll-catgenerator' plugin in _plugins folder
tag_path: "/blog/tag/"

# Pagination

paginate: 10
paginate_path: "/blog/page:num/"

# Build settings

markdown: kramdown
highlighter: rouge

# Contact links

contact:
  googleplus : 'irvin.herrerag@gmail.com'
  github: 'irvinhg'
  twitter: 'twitter'
  linkedin: 'blabla'
  facebook: ''
  blog: '/blog'

# CDN

cdn_baseurl: 'http://herrirvin.imgnx.net'

# Gems & other

gems: [jekyll-paginate]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  